# Change these first
owner: brainsys # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BrainServerOne-V1
    url: https://v1.brainsys.co.uk
  - name: BrainServerThree-V3
    url: https://v3.brainsys.co.uk
  - name: BrainServerFour-V4
    url: https://v4.brainsys.co.uk
  - name: BrainServerSix-V6
    url: http://v6.brainsys.co.uk
  - name: BrainServerSeven-V7
    url: https://v7.brainsys.co.uk
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # theme: ocean
  cname: status.brainsys.com
  #baseUrl: /upptime
  logoUrl: https://brainsys.com/wp-content/uploads/2022/04/logo68.png
  favicon: https://brainsys.com/wp-content/uploads/2022/03/favicon-32x32-1.png
  name: Brainstorm Systems
  introTitle: "BrainServer Status"
  introMessage: V1, V3 & V4 host client services. V6 is a development server & V7 is an experimental server
  navbar:
    - title: Home
      href: https://brainsys.com/
    - title: About
      href: https://brainsys.com/brainservers/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
